spring.datasource.url=jdbc:postgresql://localhost:5432/conviction
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.open-in-view=false

fmp.api-key=${FMP_API_KEY}
fmp.base-url=https://financialmodelingprep.com/stable
