spring.application.name=conviction

spring.datasource.url=jdbc:postgresql://localhost:5432/conviction
spring.datasource.username=michaelsie
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

fmp.api-key=${FMP_API_KEY}
fmp.base-url=https://financialmodelingprep.com/stable